name: Build and Deploy Docs

on:
  push:
    branches-ignore:
      - master
      - dev

jobs:
  build-docs:
    name: Install JSDoc Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Use NodeJS v16.14.2
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.2

      - name: Install jsdoc and build
        run: |
          chmod u+x scripts/build-docs.sh
          ./scripts/build-docs.sh

      - name: Debug Environment Variables
        run: cat $GITHUB_ENV

      - name: Archive Development Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs
          include-hidden-files: true
          path: docs/ph-municipalities/${{ env.version }}
          retention-days: 3

  deploy-docs:
    name: Deploy client to Github Pages
    needs: build-docs
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: docs

      - name: List files for publish
        run: ls -l -a

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
